### ISSUE TITLE
The code doesn't generate high-quality image

### ISSUE THREAD

**Issue by Trinkle23897** [roosephu/amcmcppm#1]
罗大神您好，我跑了跑您的代码，按照当前状态直接g++编译，迭代一万轮，发现噪点很大，越到后面越暗，不知道是不是有什么操作不对的地方，还是bug没修，谢谢！

**Comment by roosephu** [comment]
两年的上古代码了……我都快忘了这算法是咋整了……

你可以 show 几张图吗？我记得在某个 setting 下是有很多躁点的（光源在很远处），但是当前这个 setting 应该没问题……

**Comment by Trinkle23897** [comment]
https://cloud.tsinghua.edu.cn/d/b2241b48b7914f93bb0f/

10000张png使用ffmpeg弄成视频

**Comment by roosephu** [comment]
I found some uncommitted code. Please try the latest code, which should produce better quality images.

**Comment by Trinkle23897** [comment]
看起来应该是可以了。渲染要两三天才能走完10000轮
我们期末已经结束了，我的图形学拿了A+，在 [https://github.com/Trinkle23897/Computational-Graphics-THU-2018](https://github.com/Trinkle23897/Computational-Graphics-THU-2018)
跑这个只是因为当时在调研的时候看到了AMCMCPPM，本来也准备想写的但是来不及了，就只搞到SPPM就结束了，现在有时间就先把您的代码跑一跑看看效果，满足一下心愿
